const actionTypes = Object.freeze({
    //app
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',

    CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',

    //user
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',

    //
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
    PROCESS_LOGOUT: 'PROCESS_LOGOUT',

    // Learning Redux
    FETCH_GENDER_START: 'FETCH_GENDER_START',
    FETCH_GENDER_SUCCESS: 'FETCH_GENDER_SUCCESS',
    FETCH_GENDER_FAILED: 'FETCH_GENDER_FAILED',
    // Làm speed do lười (và cũng muốn hiểu được cách làm nhanh làm như nào!) ta sẽ bỏ qua bước start và vào thẳng bước lấy thành công và thất bại
    FETCH_POSITION_SUCCESS: 'FETCH_POSITION_SUCCESS',
    FETCH_POSITION_FAILED: 'FETCH_POSITION_FAILED',
    FETCH_ROLE_SUCCESS: 'FETCH_ROLE_SUCCESS',
    FETCH_ROLE_FAILED: 'FETCH_ROLE_FAILED',

    // Save user
    SAVE_USER_SUCCESS: 'SAVE_USER_SUCCESS',
    SAVE_USER_FAILED: 'SAVE_USER_FAILED',

    // Get info user
    GET_USER_SUCCESS: 'GET_USER_SUCCESS',
    GET_USER_FAILED: 'GET_USER_FAILED',

    // Delete user
    DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
    DELETE_USER_FAILED: 'DELETE_USER_FAILED',

    // Update user
    UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS',
    UPDATE_USER_FAILED: 'UPDATE_USER_FAILED',

    // Get data doctor home
    GET_DOCTOR_HOME_SUCCESS: 'GET_DOCTOR_HOME_SUCCESS',
    GET_DOCTOR_HOME_FAILED: 'GET_DOCTOR_HOME_FAILED',

    // Get all doctor
    GET_ALL_DOCTOR_SUCCESS: 'GET_ALL_DOCTOR_SUCCESS',
    GET_ALL_DOCTOR_FAILED: 'GET_ALL_DOCTOR_FAILED',

    // Save info doctor
    POST_SAVE_INFO_DOCTOR_SUCCESS: 'POST_SAVE_INFO_DOCTOR_SUCCESS',
    POST_SAVE_INFO_DOCTOR_FAILED: 'POST_SAVE_INFO_DOCTOR_FAILED',

    // Detail doctor
    GET_DETAIL_DOCTOR_SUCCESS: 'GET_DETAIL_DOCTOR_SUCCESS',
    GET_DETAIL_DOCTOR_FAILED: 'GET_DETAIL_DOCTOR_FAILED',

    // Save detail doctor
    SAVE_DETAIL_DOCTOR_SUCCESS: "SAVE_DETAIL_DOCTOR_SUCCESS",
    SAVE_DETAIL_DOCTOR_FAILED: 'SAVE_DETAIL_DOCTOR_FAILED',

    // Get time schedule
    GET_HOUR_SCHEDULE_DOCTOR_SUCCESS: "GET_HOUR_SCHEDULE_DOCTOR_SUCCESS",
    GET_HOUR_SCHEDULE_DOCTOR_FAILED: 'GET_HOUR_SCHEDULE_DOCTOR_FAILED',

    // Get select more info doctor
    GET_SELECT_MORE_INFO_DOCTOR_SUCCESS: "GET_SELECT_MORE_INFO_DOCTOR_SUCCESS",
    GET_SELECT_MORE_INFO_DOCTOR_FAILED: 'GET_SELECT_MORE_INFO_DOCTOR_FAILED',

    // Create more info doctor
    CREATE_MORE_INFO_DOCTOR_SUCCESS: "CREATE_MORE_INFO_DOCTOR_SUCCESS",
    CREATE_MORE_INFO_DOCTOR_FAILED: 'CREATE_MORE_INFO_DOCTOR_FAILED',

    // Edit more info doctor
    PUT_MORE_INFO_DOCTOR_SUCCESS: "PUT_MORE_INFO_DOCTOR_SUCCESS",
    PUT_MORE_INFO_DOCTOR_FAILED: 'PUT_MORE_INFO_DOCTOR_FAILED',

    // Get more info doctor
    GET_MORE_INFO_DOCTOR_SUCCESS: "GET_MORE_INFO_DOCTOR_SUCCESS",
    GET_MORE_INFO_DOCTOR_FAILED: 'GET_MORE_INFO_DOCTOR_FAILED',

    // Get profile doctor by id
    GET_PROFILE_DOCTOR_BY_ID_SUCCESS: "GET_PROFILE_DOCTOR_BY_ID_SUCCESS",
    GET_PROFILE_DOCTOR_BY_ID_FAILED: 'GET_PROFILE_DOCTOR_BY_ID_FAILED',

    // Post book appointment
    POST_BOOKING_APPOINTMENT_SUCCESS: "POST_BOOKING_APPOINTMENT_SUCCESS",
    POST_BOOKING_APPOINTMENT_FAILED: 'POST_BOOKING_APPOINTMENT_FAILED',

    // Get all specialty
    GET_ALL_SPECIALTY_SUCCESS: "GET_ALL_SPECIALTY_SUCCESS",
    GET_ALL_SPECIALTY_FAILED: 'GET_ALL_SPECIALTY_FAILED',

    // Get all province
    GET_ALL_PROVINCE_SUCCESS: "GET_ALL_PROVINCE_SUCCESS",
    GET_ALL_PROVINCE_FAILED: 'GET_ALL_PROVINCE_FAILED',

    // Get all clinic
    GET_ALL_CLINIC_SUCCESS: "GET_ALL_CLINIC_SUCCESS",
    GET_ALL_CLINIC_FAILED: 'GET_ALL_CLINIC_FAILED',

    // Get patient for doctor
    GET_PATIENT_FOR_DOCTOR_SUCCESS: "GET_PATIENT_FOR_DOCTOR_SUCCESS",
    GET_PATIENT_FOR_DOCTOR_FAILED: 'GET_PATIENT_FOR_DOCTOR_FAILED',

    // Post send remedy
    POST_SEND_REMEDY_SUCCESS: "POST_SEND_REMEDY_SUCCESS",
    POST_SEND_REMEDY_FAILED: 'POST_SEND_REMEDY_FAILED',
})

export default actionTypes;